### ISSUE TITLE
BUG : flush() function is improperly typed in index.d.ts

### ISSUE THREAD

**Issue by DanielSidhion** [rudderlabs/rudder-sdk-node#117]
`index.d.ts` has the following type for `flush()`: `flush(callback?: Function): Analytics;`. However, the code actually returns a Promise, so its return type should be changed to something more appropriate that at least includes `Promise<>`.

I came upon this when improving my team's linting configs and making things stricter. I'm using rudder-sdk-node 2.0.4.

**Comment by bardisg** [comment]
Hello @DanielSidhion,

Thank you for raising this issue. We will plan it and fix in the upcoming sprint.

Will update you once completed.

**Comment by MoumitaM** [comment]
Released the fix. Use the latest version 2.0.5
