### ISSUE TITLE
BUG : Info log level has a lower priority than debug

### ISSUE THREAD

**Issue by lox** [rudderlabs/rudder-sdk-node#122]
We are creating our client like this:

```
    analyticsClient = new RudderAnalytics(process.env.RUDDERSTACK_WRITE_KEY ?? '', {
      dataPlaneUrl: process.env.RUDDERSTACK_DATA_PLANE_URL,
      logLevel: 'info',
      flushAt: 1,
    })
```

Still seeing log messages like:

```
[Rudder] debug: flushAt reached, trying flush...
[Rudder] debug: in flush
[Rudder] debug: in flush
```

We are running: `"@rudderstack/rudder-sdk-node": "^2.0.4",`

**Comment by MoumitaM** [comment]
@lox , Apologies for the delay, I will look into it.

**Comment by MoumitaM** [comment]
@lox, Currently in our SDK log level `info` has a **lower priority** than `debug`. So all the higher priority errors along with `info` will be printed. 
Do you think that's the concern?

**Comment by lox** [comment]
I'm not sure I understand, are you saying that `info` < `debug` on your logger levels? If so, that seems very odd. 🤔

**Comment by lox** [comment]
Oh wow, yeah you are right:

https://github.com/rudderlabs/rudder-sdk-node/blob/48a9c6c57df553ced1e4a76b640cd0c1dce1b57a/src/Logger.js#L2-L9

Looks like it was introduced by @bardisg in https://github.com/rudderlabs/rudder-sdk-node/commit/36192471055fdfc2032223986267715c2b48d4c4 when winston was extracted. I'd hazard a guess that is a mistake / typo, as the more conventional logger levels from winston are:

https://github.com/winstonjs/winston#logging
```
const levels = {
  error: 0,
  warn: 1,
  info: 2,
  http: 3,
  verbose: 4,
  debug: 5,
  silly: 6
};
```

**Comment by lox** [comment]
I updated the title to reflect the issue better!

**Comment by MoumitaM** [comment]
@lox, This issue has been fixed and released. Check out 2.0.6
