### ISSUE TITLE
.d.ts file not included in `npm install`

### ISSUE THREAD

**Issue by Derrreks** [rudderlabs/rudder-sdk-node#57]
After running `npm install @rudderstack/rudder-sdk-node`, it seems that the `.d.ts` file is not included:

All the included files:
<img width="365" alt="Screen Shot 2022-01-20 at 12 42 05 PM" src="https://user-images.githubusercontent.com/11246424/150419005-8bbee245-ec03-4f24-ad4a-b9f0d1dc8c06.png">

**Comment by Derrreks** [comment]
It's possible that the `types` decleration needs to be included in `package.json`: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html.

**Comment by saikumarrs** [comment]
@Derrreks Thanks for notifying us. We've re-published a new SDK version (v1.0.12) to NPM with the declaration file included for now. Therefore, we'll be closing this issue.
