### ISSUE TITLE
Documentation link on README is broken

### ISSUE THREAD

**Issue by tirish** [rudderlabs/rudder-sdk-node#60]
The link on the README for more documentation is broken and directs to: https://docs.rudderstack.com/rudderstack-sdk-integration-guides/rudderstack-node-sdk

If there is some additional documentation would be great to get that link updated. Thanks!

EDIT: Looks like the updated URL may be this: https://www.rudderstack.com/docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-node-sdk/

**Comment by MoumitaM** [comment]
Thank you for bringing this up. We are working on it, as soon as we release the changes will update you here.

**Comment by MoumitaM** [comment]
Hi @tirish,
Apologies for the delayed response. The README has been updated long ago.
