### ISSUE TITLE
In serverless environment some events are dropped

### ISSUE THREAD

**Issue by thibaultleouay** [rudderlabs/rudder-sdk-node#79]
Hello

I'm using this SDK in a vercel function and some events are dropped.

I have set up
```
Flushat:1

```
And explicitly call flush at the end 

Do you have some best practices for serverless environment?

Thanks

**Comment by MoumitaM** [comment]
Hi @thibaultleouay, Apologies for the delayed response. 
Can you try the latest version and let us know if that has solved your problem?

**Comment by MoumitaM** [comment]
Closing this issue hoping the last release solved the issue and there is no further response from the user.
