### ISSUE TITLE
Failure to Get Active Jobs when Creating Persistence Queue

### ISSUE THREAD

**Issue by ppoddar-affordably** [rudderlabs/rudder-sdk-node#82]
Hi, I’m using the Persistence Queue for the Rudderstack NodeJS library (via Redis via Bull). I’m getting an error when calling createPersistenceQueue of `[Rudder] error: failed geting active jobs`. The docs on https://www.rudderstack.com/docs/sources/event-streams/sdks/rudderstack-node-sdk/#nodejs-sdk-data-persistence say:
If the callback returns with an error, we recommend retrying calling createPersistenceQueue with a backoff.

Is there anymore visibility on why this is failing and why we should continually retry?

For more info, I don’t see `this.logger.debug("success geting active jobs");` printed in my logs — suggesting that the failing call was:
`this.pQueue.getActive()`
But the actual error gets eaten up

Source: https://cs.github.com/rudderlabs/rudder-sdk-node/blob/a8b8f4f5d590561f76fc0d05f23be1f08414b098/index.js#L649

**Comment by MoumitaM** [comment]
Hi @ppoddar-affordably, Thank you for raising this. We will look into it shortly and update you.

**Comment by MoumitaM** [comment]
Hi @ppoddar-affordably, 
Could you give me a little information on the below things:

1. Check your Redis connection and confirm it is working.
2. Share your `createPersistenceQueue` method implementation.

**Comment by MoumitaM** [comment]
We are closing this as there is no communication from the end user.
