### ISSUE TITLE
v2.0.0 exception: "Error: Not Found".

### ISSUE THREAD

**Issue by csuermann** [rudderlabs/rudder-sdk-node#88]
After updating to v2.0.0 my Node app crashes with the not very helpful exception "Error: Not Found".

````
Error: Not Found
  File "app:///../../node_modules/@rudderstack/rudder-sdk-node/index.js", line 749, col 33, in <anonymous>
    var error = new Error(err.response.statusText);
  File "node:internal/process/task_queues", line 95, col 5, in process.processTicksAndRejections
````

Seems to originate from [this line](https://github.com/rudderlabs/rudder-sdk-node/blob/master/index.js#L726).

This code used to work with v1.1.4:

```typescript
const rudderClient: new Analytics('my-write-key', 'https://xxxxx.dataplane.rudderstack.com/v1/batch')
//...
rudderClient.track(/** some event **/)
```

It got adopted to comply with the breaking change introduced in v2.0.0 like this:

```typescript
const rudderClient: Analytics('my-write-key', { dataPlaneUrl: 'https://xxxxx.dataplane.rudderstack.com/v1/batch' })
//...
rudderClient.track(/** some event **/)
```

**Comment by csuermann** [comment]
I figured it out: In v2.0.0 there are actually 2 breaking changes:

1. `dataPlaneUrl` has to be passed in options instead as an argument in initialization.
2. `dataPlaneUrl` must no longer include the path `/v1/batch`. This parameter is therefore no longer a URL but rather a hostname despite its name.

While 1 was mentioned in the release notes, 2 was not. Might be worth calling this out more explicitly. Even better would be if such unnecessary (?) breaking changes could be avoided altogether.

**Comment by MoumitaM** [comment]
@csuermann, We have updated the changelog. Thank you for raising this.
